name: Terraform Apply and Get CLIENT_ID

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init ./module

    - name: Terraform Plan
      run: terraform plan ./module

    - name: Terraform Apply
      run: terraform apply -auto-approve ./module

    - name: Set up PowerShell
      uses: PowerShell/setup-powershell@v0
      with:
        pwsh-version: '7.x'

    - name: Run PowerShell script
      run: |
        .\check.ps1
      env:
        TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
        TFC_ORG_NAME: Shubhendu
