name: Terraform Apply and Get CLIENT_ID

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.2
        cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Run PowerShell script
      shell: pwsh
      run: |
        .\check.ps1
      env:
        TFC_API_TOKEN: ${{ secrets.TFC_API_TOKEN }}
        TFC_ORG_NAME: Shubhendu
